on: [push]

name: Telegram Notify Push

jobs:

  build:
    runs-on: ubuntu-latest
    name: Telegram Notify Push
    steps:
    - name: Telegram Notify Push
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      with:
        args: "{{ repo }}： 一个新 commit"
